In [1]:
import re
import numpy as np
import pprint as pp

def tokenize(text):
    # obtains tokens with a least 1 alphabet
    pattern = re.compile(r'[A-Za-z]+[\w^\']*|[\w^\']*[A-Za-z]+[\w^\']*')
    return pattern.findall(text.lower())  

In [2]:
text = "natural language processing and machine learning is fun and exciting"
tokens = tokenize(text)
#pp.pprint(tokens)

In [3]:
wordCounts= {}
for eachWord in tokens:
    if eachWord in wordCounts.keys():
        wordCounts[eachWord] += 1
    else:
        wordCounts[eachWord] = 1
#wordCounts

In [4]:
word2index = {}
word2index = dict ((word, i) for i, word in enumerate(wordCounts.keys()))
# word2index 

Need to generate target word and context word based on window size. Each of these words are to be represented as one hot vectors. One hot vector is of dimension = (# of unique tokens in text) and has 1 in position of word under consideration.

In [5]:
params = {
    'window':3,
    'embed_dim':10,
    'N':len(tokens), #number of tokens
    'V':len(word2index), #number of unique words in the vocab
    'Ed':10,
    'Lr':0.1,
    'epochs':10000
}

In [6]:
def getOneHotVector(word, word2index):
    oneHot = np.zeros(len(word2index))
    wordInd = word2index[word]
    oneHot[wordInd] = 1
    return oneHot
a = getOneHotVector('language', word2index)
a.shape

(9,)

In [7]:
w = params['window']
N = params['N']
training_data = []
for i in range(N):
    w_target = getOneHotVector(tokens[i], word2index)
    contextIndices = list(range(max(0, i-w), i)) + list(range(i+1, min(i+w+1, N)))
    w_context = []
    for eachContextIndex in contextIndices:
        w_context.append(getOneHotVector(tokens[eachContextIndex], word2index))
    training_data.append([w_target, w_context])

In [8]:
training_data

[[array([1., 0., 0., 0., 0., 0., 0., 0., 0.]),
  [array([0., 1., 0., 0., 0., 0., 0., 0., 0.]),
   array([0., 0., 1., 0., 0., 0., 0., 0., 0.]),
   array([0., 0., 0., 1., 0., 0., 0., 0., 0.])]],
 [array([0., 1., 0., 0., 0., 0., 0., 0., 0.]),
  [array([1., 0., 0., 0., 0., 0., 0., 0., 0.]),
   array([0., 0., 1., 0., 0., 0., 0., 0., 0.]),
   array([0., 0., 0., 1., 0., 0., 0., 0., 0.]),
   array([0., 0., 0., 0., 1., 0., 0., 0., 0.])]],
 [array([0., 0., 1., 0., 0., 0., 0., 0., 0.]),
  [array([1., 0., 0., 0., 0., 0., 0., 0., 0.]),
   array([0., 1., 0., 0., 0., 0., 0., 0., 0.]),
   array([0., 0., 0., 1., 0., 0., 0., 0., 0.]),
   array([0., 0., 0., 0., 1., 0., 0., 0., 0.]),
   array([0., 0., 0., 0., 0., 1., 0., 0., 0.])]],
 [array([0., 0., 0., 1., 0., 0., 0., 0., 0.]),
  [array([1., 0., 0., 0., 0., 0., 0., 0., 0.]),
   array([0., 1., 0., 0., 0., 0., 0., 0., 0.]),
   array([0., 0., 1., 0., 0., 0., 0., 0., 0.]),
   array([0., 0., 0., 0., 1., 0., 0., 0., 0.]),
   array([0., 0., 0., 0., 0., 1., 0., 

##### Training data is ready. Build the network structure. Ignoring the bias terms, I need:
    - Hidden layer weights
    - Output layer weights
    
##### What does the NN do?
    - Since this is a skipgram model, it predicts the context words given a center word.

##### What is the output of NN?
    - Output is the probability distribution over all the unique words such that the context words will have high probability than non context words.
    
##### What is the shape of weight matrices of hidden and output layer?
    - Embedding dimensions is provided in the parameters as Ed
    - Input Vector = [V,1]
    - Wh = [V, Ed]
    - Wo = [Ed, V]
    - Output Vector = [V, Ed]
    
##### Why dont we have an activation function in the hidden layer?

In [9]:
params['Wh'] = np.random.uniform(-1,1,(params['V'], params['Ed']))
print('Hidden layer weights Wh:', params['Wh'].shape)
params['Wo'] = np.random.uniform(-1,1,(params['Ed'], params['V']))
print('Output layer weights Wo:', params['Wo'].shape)
params['Wh'] 
params['Wo']

Hidden layer weights Wh: (9, 10)
Output layer weights Wo: (10, 9)


array([[-0.0676114 ,  0.68857534, -0.8924202 , -0.82839605,  0.68152572,
         0.00257424, -0.36013001, -0.46975061, -0.86721951],
       [ 0.15165494,  0.02267613, -0.33423338, -0.39161091,  0.77521506,
         0.97980448, -0.83557118,  0.5730265 ,  0.00320183],
       [ 0.07218461,  0.66497996, -0.42133111, -0.22804522, -0.6280436 ,
         0.62114312,  0.82116103,  0.16125765, -0.22479689],
       [-0.15132406,  0.27727443,  0.84469449,  0.63922409,  0.25601281,
        -0.52426068, -0.53823786, -0.74410497, -0.68221234],
       [-0.23204985, -0.32141216, -0.47578448, -0.23548055,  0.88689939,
        -0.29940789, -0.72601733,  0.10321062,  0.3667019 ],
       [ 0.11485066, -0.95554856,  0.10859713,  0.77782798, -0.70649008,
        -0.78581115,  0.67257709,  0.93467395, -0.1365687 ],
       [ 0.30212152,  0.87315748, -0.10217679, -0.07413153,  0.39726299,
        -0.4991837 , -0.99824058, -0.89042076,  0.16505447],
       [-0.03337596, -0.16718992,  0.92996316,  0.45157786, -0

In [10]:
def forwardPass(inputVector, Wh, Wo):
    h = np.dot(Wh.T, inputVector)
#     print('Wh Shape:',Wh.shape)
#     print('Input Vector shape:', inputVector.shape)
#     print('input vector:',inputVector)
    u = np.dot(Wo.T, h)
    o = softmax(u)
#     print(o)
    return h,u,o

In [11]:
def softmax(x):
    sm = np.exp(x)/np.exp(x).sum()
    return sm

In [12]:
def backProp(error, h, target):
    dl_dw2 = np.outer(h, error)
    dl_dw1 = np.outer(target, np.dot(params['Wo'], error.T))
    # Update weights
    params['Wh'] = params['Wh'] - (params['Lr'] * dl_dw1)
    params['Wo'] = params['Wo'] - (params['Lr'] * dl_dw2)

In [13]:
inits = params['Wh']
inits[0]

array([-0.5572125 , -0.64269345,  0.29576338,  0.4178194 ,  0.89434003,
       -0.15172811,  0.39749312,  0.8132315 ,  0.55131691,  0.99414663])

In [14]:
for i in range(params['epochs']):
    loss = 0
    for target, context in training_data:
        h, u, o = forwardPass(target, params['Wh'], params['Wo'])
        error = 0
#         error = np.sum([np.subtract(o, ec) for ec in context ], axis=0)
        for eachContext in context:
            error += np.subtract(o, eachContext)
        backProp(error, h, target)
        loss += -np.sum([u[word.tolist().index(1)] for word in context]) + len(context) * np.log(np.sum(np.exp(u)))
    print('Epoch:', i, ' Loss:', loss)


Epoch: 0  Loss: 123.95218209300884
Epoch: 1  Loss: 102.18881159617877
Epoch: 2  Loss: 96.82119386481926
Epoch: 3  Loss: 93.6850546267322
Epoch: 4  Loss: 91.4799772830763
Epoch: 5  Loss: 89.76598852021593
Epoch: 6  Loss: 88.36967400584508
Epoch: 7  Loss: 87.20817002501639
Epoch: 8  Loss: 86.23031981161061
Epoch: 9  Loss: 85.40060008063207
Epoch: 10  Loss: 84.69388093013559
Epoch: 11  Loss: 84.09148964661871
Epoch: 12  Loss: 83.57818826158056
Epoch: 13  Loss: 83.140610922024
Epoch: 14  Loss: 82.76681114682732
Epoch: 15  Loss: 82.4462656915007
Epoch: 16  Loss: 82.1699254084988
Epoch: 17  Loss: 81.93018232560895
Epoch: 18  Loss: 81.7207545792371
Epoch: 19  Loss: 81.53652000088695
Epoch: 20  Loss: 81.37332962196245
Epoch: 21  Loss: 81.22782637566326
Epoch: 22  Loss: 81.09728569610506
Epoch: 23  Loss: 80.97948447739883
Epoch: 24  Loss: 80.87259770668766
Epoch: 25  Loss: 80.77511821401332
Epoch: 26  Loss: 80.68579448304068
Epoch: 27  Loss: 80.60358195774528
Epoch: 28  Loss: 80.5276045797643
E

Epoch: 313  Loss: 79.37893363924722
Epoch: 314  Loss: 79.29576109807437
Epoch: 315  Loss: 79.37423987588957
Epoch: 316  Loss: 79.29221378408414
Epoch: 317  Loss: 79.37003357591674
Epoch: 318  Loss: 79.29012548478462
Epoch: 319  Loss: 79.36712086707017
Epoch: 320  Loss: 79.29008039705202
Epoch: 321  Loss: 79.36638193217232
Epoch: 322  Loss: 79.29250647803838
Epoch: 323  Loss: 79.36854200422385
Epoch: 324  Loss: 79.29751826927725
Epoch: 325  Loss: 79.37400469155355
Epoch: 326  Loss: 79.3048105755461
Epoch: 327  Loss: 79.38298925256868
Epoch: 328  Loss: 79.31368494075289
Epoch: 329  Loss: 79.39613212700783
Epoch: 330  Loss: 79.3231651500673
Epoch: 331  Loss: 79.41514051367876
Epoch: 332  Loss: 79.33174390801398
Epoch: 333  Loss: 79.44129238390114
Epoch: 334  Loss: 79.33582101656886
Epoch: 335  Loss: 79.46810238311379
Epoch: 336  Loss: 79.32910972595872
Epoch: 337  Loss: 79.47572407081613
Epoch: 338  Loss: 79.31294147239622
Epoch: 339  Loss: 79.45093393434786
Epoch: 340  Loss: 79.309825232

Epoch: 563  Loss: 78.98004750994815
Epoch: 564  Loss: 79.08261238930989
Epoch: 565  Loss: 78.9764383531309
Epoch: 566  Loss: 79.013469385296
Epoch: 567  Loss: 78.87425349259226
Epoch: 568  Loss: 78.97739205617457
Epoch: 569  Loss: 78.94096365395689
Epoch: 570  Loss: 79.1174506919071
Epoch: 571  Loss: 79.34543115894442
Epoch: 572  Loss: 79.59292373068259
Epoch: 573  Loss: 79.55517233567213
Epoch: 574  Loss: 79.56923065611974
Epoch: 575  Loss: 79.43589298890197
Epoch: 576  Loss: 79.70103512585159
Epoch: 577  Loss: 80.07849635986544
Epoch: 578  Loss: 80.24572287071086
Epoch: 579  Loss: 80.40484663311969
Epoch: 580  Loss: 80.40284620983863
Epoch: 581  Loss: 79.8511666467761
Epoch: 582  Loss: 79.74817225265342
Epoch: 583  Loss: 79.80525897900128
Epoch: 584  Loss: 79.70969881705186
Epoch: 585  Loss: 79.78090137724627
Epoch: 586  Loss: 79.66336059474783
Epoch: 587  Loss: 79.63233301831073
Epoch: 588  Loss: 79.41157154906618
Epoch: 589  Loss: 79.37771303002424
Epoch: 590  Loss: 79.145850007351

Epoch: 898  Loss: 79.05949927799676
Epoch: 899  Loss: 79.16611062620534
Epoch: 900  Loss: 79.00734336272811
Epoch: 901  Loss: 79.09232182855544
Epoch: 902  Loss: 78.99779506906398
Epoch: 903  Loss: 79.23587148904642
Epoch: 904  Loss: 79.13598777078833
Epoch: 905  Loss: 79.37610076981886
Epoch: 906  Loss: 79.34624485280362
Epoch: 907  Loss: 79.60198255327074
Epoch: 908  Loss: 79.49533323236044
Epoch: 909  Loss: 79.57664611704928
Epoch: 910  Loss: 79.55633399230727
Epoch: 911  Loss: 79.70361538871765
Epoch: 912  Loss: 79.83974814410612
Epoch: 913  Loss: 79.90593900379288
Epoch: 914  Loss: 80.00442583881629
Epoch: 915  Loss: 79.98416829543169
Epoch: 916  Loss: 79.60197257196509
Epoch: 917  Loss: 79.56638049259698
Epoch: 918  Loss: 79.50950768176807
Epoch: 919  Loss: 79.52804037879744
Epoch: 920  Loss: 79.4779856570113
Epoch: 921  Loss: 79.55407360009886
Epoch: 922  Loss: 79.47457800125157
Epoch: 923  Loss: 79.43544490043753
Epoch: 924  Loss: 79.28606333669057
Epoch: 925  Loss: 79.14589474

Epoch: 1164  Loss: 79.10292529829506
Epoch: 1165  Loss: 79.14277517566074
Epoch: 1166  Loss: 79.26041561029452
Epoch: 1167  Loss: 79.40257720542317
Epoch: 1168  Loss: 79.57990354237384
Epoch: 1169  Loss: 79.74497525480932
Epoch: 1170  Loss: 79.8780420381362
Epoch: 1171  Loss: 79.87094470202867
Epoch: 1172  Loss: 79.87151612674393
Epoch: 1173  Loss: 79.68443617133806
Epoch: 1174  Loss: 79.68450201517774
Epoch: 1175  Loss: 79.50662527918375
Epoch: 1176  Loss: 79.5325201304857
Epoch: 1177  Loss: 79.52431980269311
Epoch: 1178  Loss: 79.52171350968314
Epoch: 1179  Loss: 79.56421810636633
Epoch: 1180  Loss: 79.57304605909864
Epoch: 1181  Loss: 79.6170974032275
Epoch: 1182  Loss: 79.53821188272632
Epoch: 1183  Loss: 79.64658957411952
Epoch: 1184  Loss: 79.35870991698302
Epoch: 1185  Loss: 79.50465359511554
Epoch: 1186  Loss: 79.17382223784705
Epoch: 1187  Loss: 79.28733520286613
Epoch: 1188  Loss: 79.1061963198309
Epoch: 1189  Loss: 79.28107999114677
Epoch: 1190  Loss: 79.16189608121068
Epoch

Epoch: 1492  Loss: 79.65803130048708
Epoch: 1493  Loss: 79.53229553641856
Epoch: 1494  Loss: 79.56932638763521
Epoch: 1495  Loss: 79.53852843256692
Epoch: 1496  Loss: 79.67806386384139
Epoch: 1497  Loss: 79.69426040226644
Epoch: 1498  Loss: 79.74682657877773
Epoch: 1499  Loss: 79.70875398252177
Epoch: 1500  Loss: 79.7243686800975
Epoch: 1501  Loss: 79.71937779635057
Epoch: 1502  Loss: 79.76971072583979
Epoch: 1503  Loss: 79.71343377907046
Epoch: 1504  Loss: 79.69738115769864
Epoch: 1505  Loss: 79.56291889078827
Epoch: 1506  Loss: 79.56920248592999
Epoch: 1507  Loss: 79.50571425614123
Epoch: 1508  Loss: 79.63547013304039
Epoch: 1509  Loss: 79.65797700105782
Epoch: 1510  Loss: 79.74187106471919
Epoch: 1511  Loss: 79.71314730092617
Epoch: 1512  Loss: 79.72372965887644
Epoch: 1513  Loss: 79.71139430703664
Epoch: 1514  Loss: 79.76800724566078
Epoch: 1515  Loss: 79.73405726912277
Epoch: 1516  Loss: 79.73284433349384
Epoch: 1517  Loss: 79.5991228012827
Epoch: 1518  Loss: 79.58402192638337
Epo

Epoch: 1780  Loss: 80.23628621748118
Epoch: 1781  Loss: 80.1997695005291
Epoch: 1782  Loss: 80.13155487050918
Epoch: 1783  Loss: 80.00151110743798
Epoch: 1784  Loss: 80.00277015078393
Epoch: 1785  Loss: 79.82810609107224
Epoch: 1786  Loss: 79.80982895000281
Epoch: 1787  Loss: 79.66600576164144
Epoch: 1788  Loss: 79.62279218730508
Epoch: 1789  Loss: 79.62447447511319
Epoch: 1790  Loss: 79.63061129305706
Epoch: 1791  Loss: 79.65652712853858
Epoch: 1792  Loss: 79.85052216324357
Epoch: 1793  Loss: 79.90879688527184
Epoch: 1794  Loss: 79.8775542881734
Epoch: 1795  Loss: 79.78071978392187
Epoch: 1796  Loss: 79.8056856356079
Epoch: 1797  Loss: 79.7238777506765
Epoch: 1798  Loss: 79.66745099408234
Epoch: 1799  Loss: 79.5179747692155
Epoch: 1800  Loss: 79.54529295186568
Epoch: 1801  Loss: 79.47956338771064
Epoch: 1802  Loss: 79.47557027219052
Epoch: 1803  Loss: 79.46744926387021
Epoch: 1804  Loss: 79.63360462849131
Epoch: 1805  Loss: 79.73005533510104
Epoch: 1806  Loss: 79.76361136205276
Epoch:

Epoch: 2069  Loss: 79.49940210190513
Epoch: 2070  Loss: 79.56626395273229
Epoch: 2071  Loss: 79.58453351803453
Epoch: 2072  Loss: 79.63291318816144
Epoch: 2073  Loss: 79.59310093723519
Epoch: 2074  Loss: 79.678308621325
Epoch: 2075  Loss: 79.70244619261805
Epoch: 2076  Loss: 79.90906824046196
Epoch: 2077  Loss: 79.76561070855684
Epoch: 2078  Loss: 79.84421272852822
Epoch: 2079  Loss: 79.74735825705581
Epoch: 2080  Loss: 79.81556605791319
Epoch: 2081  Loss: 79.70819160913798
Epoch: 2082  Loss: 79.76585440956484
Epoch: 2083  Loss: 79.66902090890966
Epoch: 2084  Loss: 79.7325368514903
Epoch: 2085  Loss: 79.81148817368192
Epoch: 2086  Loss: 79.68967738565466
Epoch: 2087  Loss: 79.75631446933932
Epoch: 2088  Loss: 79.9009484136258
Epoch: 2089  Loss: 79.87265012977137
Epoch: 2090  Loss: 79.94558179582127
Epoch: 2091  Loss: 79.85493887718579
Epoch: 2092  Loss: 79.77934650739428
Epoch: 2093  Loss: 79.64011229359956
Epoch: 2094  Loss: 79.67855052360582
Epoch: 2095  Loss: 79.49437021291158
Epoch

Epoch: 2373  Loss: 79.6038352476572
Epoch: 2374  Loss: 79.8219179029455
Epoch: 2375  Loss: 79.78085611935359
Epoch: 2376  Loss: 79.85869676589634
Epoch: 2377  Loss: 79.74913007158199
Epoch: 2378  Loss: 79.92035865833664
Epoch: 2379  Loss: 79.79491238188332
Epoch: 2380  Loss: 79.82497323741352
Epoch: 2381  Loss: 79.60807938250794
Epoch: 2382  Loss: 79.67266835908428
Epoch: 2383  Loss: 79.60005152977146
Epoch: 2384  Loss: 79.45536875938522
Epoch: 2385  Loss: 79.39028867357592
Epoch: 2386  Loss: 79.61792560946728
Epoch: 2387  Loss: 79.66446088519444
Epoch: 2388  Loss: 79.87959689723418
Epoch: 2389  Loss: 79.83140700179888
Epoch: 2390  Loss: 79.87065027187131
Epoch: 2391  Loss: 79.78616289135417
Epoch: 2392  Loss: 79.96114726189936
Epoch: 2393  Loss: 79.74651793245546
Epoch: 2394  Loss: 79.702194815036
Epoch: 2395  Loss: 79.54961785265618
Epoch: 2396  Loss: 79.6205456008186
Epoch: 2397  Loss: 79.53134659016155
Epoch: 2398  Loss: 79.45554638015594
Epoch: 2399  Loss: 79.44435052241961
Epoch:

Epoch: 2671  Loss: 79.68499185736532
Epoch: 2672  Loss: 79.92103542031663
Epoch: 2673  Loss: 80.02587589487902
Epoch: 2674  Loss: 80.04205225363629
Epoch: 2675  Loss: 80.01379665776712
Epoch: 2676  Loss: 80.21783705259485
Epoch: 2677  Loss: 79.96778114795671
Epoch: 2678  Loss: 79.82361179654201
Epoch: 2679  Loss: 79.60227015252387
Epoch: 2680  Loss: 79.60318298078327
Epoch: 2681  Loss: 79.43471255912056
Epoch: 2682  Loss: 79.47667751930705
Epoch: 2683  Loss: 79.42077106685987
Epoch: 2684  Loss: 79.51700795932953
Epoch: 2685  Loss: 79.68656477607978
Epoch: 2686  Loss: 79.90418815078965
Epoch: 2687  Loss: 79.96402894200948
Epoch: 2688  Loss: 79.92232897974955
Epoch: 2689  Loss: 79.86877770388733
Epoch: 2690  Loss: 80.12793131419173
Epoch: 2691  Loss: 79.88290478288762
Epoch: 2692  Loss: 79.75698459595831
Epoch: 2693  Loss: 79.5844519109548
Epoch: 2694  Loss: 79.60273323460713
Epoch: 2695  Loss: 79.39337616745316
Epoch: 2696  Loss: 79.45536370616068
Epoch: 2697  Loss: 79.33227197421073
Ep

Epoch: 2959  Loss: 79.6026415617671
Epoch: 2960  Loss: 79.61356169611723
Epoch: 2961  Loss: 79.43126284409392
Epoch: 2962  Loss: 79.46998784036496
Epoch: 2963  Loss: 79.43052784176926
Epoch: 2964  Loss: 79.51054451797077
Epoch: 2965  Loss: 79.66437149128957
Epoch: 2966  Loss: 79.95298542688816
Epoch: 2967  Loss: 80.11184685221015
Epoch: 2968  Loss: 80.11527958126675
Epoch: 2969  Loss: 80.06958057624895
Epoch: 2970  Loss: 80.2835814013865
Epoch: 2971  Loss: 79.99642202166245
Epoch: 2972  Loss: 79.85626045237655
Epoch: 2973  Loss: 79.63977816774045
Epoch: 2974  Loss: 79.5929664799478
Epoch: 2975  Loss: 79.378622211026
Epoch: 2976  Loss: 79.49618251726301
Epoch: 2977  Loss: 79.43658430517841
Epoch: 2978  Loss: 79.55497963855643
Epoch: 2979  Loss: 79.74949552402217
Epoch: 2980  Loss: 79.75910131474143
Epoch: 2981  Loss: 79.77501000770914
Epoch: 2982  Loss: 79.89220448781346
Epoch: 2983  Loss: 79.80343471232656
Epoch: 2984  Loss: 80.01313516250714
Epoch: 2985  Loss: 79.77557555614726
Epoch:

Epoch: 3288  Loss: 79.72651513955914
Epoch: 3289  Loss: 79.79957313076821
Epoch: 3290  Loss: 79.8084756651409
Epoch: 3291  Loss: 79.7465319876685
Epoch: 3292  Loss: 80.00584948819666
Epoch: 3293  Loss: 79.74182938278703
Epoch: 3294  Loss: 79.69820954980482
Epoch: 3295  Loss: 79.54594663741112
Epoch: 3296  Loss: 79.5401827470436
Epoch: 3297  Loss: 79.3646841011846
Epoch: 3298  Loss: 79.44265949662568
Epoch: 3299  Loss: 79.34222479445836
Epoch: 3300  Loss: 79.42846739869191
Epoch: 3301  Loss: 79.62323341829318
Epoch: 3302  Loss: 79.85649546474708
Epoch: 3303  Loss: 79.98719046447297
Epoch: 3304  Loss: 79.96586494990397
Epoch: 3305  Loss: 79.98228858961228
Epoch: 3306  Loss: 80.23308931275614
Epoch: 3307  Loss: 79.8823492216706
Epoch: 3308  Loss: 79.76787247984814
Epoch: 3309  Loss: 79.6176790002702
Epoch: 3310  Loss: 79.55760785403014
Epoch: 3311  Loss: 79.37789330317409
Epoch: 3312  Loss: 79.4901719112981
Epoch: 3313  Loss: 79.42281352447344
Epoch: 3314  Loss: 79.44075541673948
Epoch: 3

Epoch: 3557  Loss: 79.96303846495309
Epoch: 3558  Loss: 80.25663924360931
Epoch: 3559  Loss: 79.99160712913823
Epoch: 3560  Loss: 79.84558413457827
Epoch: 3561  Loss: 79.62558311951531
Epoch: 3562  Loss: 79.6576390666328
Epoch: 3563  Loss: 79.477657498403
Epoch: 3564  Loss: 79.55550622117515
Epoch: 3565  Loss: 79.41479339173247
Epoch: 3566  Loss: 79.48542431088238
Epoch: 3567  Loss: 79.61755916129837
Epoch: 3568  Loss: 79.77003963586372
Epoch: 3569  Loss: 79.83861539790061
Epoch: 3570  Loss: 79.78825748457895
Epoch: 3571  Loss: 79.74174351269775
Epoch: 3572  Loss: 80.02747422118017
Epoch: 3573  Loss: 79.81269700962591
Epoch: 3574  Loss: 79.7330483402027
Epoch: 3575  Loss: 79.55947735661948
Epoch: 3576  Loss: 79.59561961970205
Epoch: 3577  Loss: 79.407358037736
Epoch: 3578  Loss: 79.4372659451762
Epoch: 3579  Loss: 79.2751352949669
Epoch: 3580  Loss: 79.39034667075414
Epoch: 3581  Loss: 79.47590404154128
Epoch: 3582  Loss: 79.70452984893109
Epoch: 3583  Loss: 79.80154405863384
Epoch: 35

Epoch: 3893  Loss: 80.08476664660243
Epoch: 3894  Loss: 79.85049124816369
Epoch: 3895  Loss: 79.8643817727048
Epoch: 3896  Loss: 80.18577764322121
Epoch: 3897  Loss: 80.03976284253535
Epoch: 3898  Loss: 80.0360600604771
Epoch: 3899  Loss: 79.75629558324042
Epoch: 3900  Loss: 79.77307893622329
Epoch: 3901  Loss: 79.70291686712103
Epoch: 3902  Loss: 79.67594677856539
Epoch: 3903  Loss: 79.50781468727034
Epoch: 3904  Loss: 79.56499612932348
Epoch: 3905  Loss: 79.61058701021402
Epoch: 3906  Loss: 79.66223550207137
Epoch: 3907  Loss: 79.8190043791515
Epoch: 3908  Loss: 79.95021784659441
Epoch: 3909  Loss: 80.04639431114185
Epoch: 3910  Loss: 80.14935734590281
Epoch: 3911  Loss: 80.10959790458642
Epoch: 3912  Loss: 80.23167820484974
Epoch: 3913  Loss: 80.01354960754979
Epoch: 3914  Loss: 79.87835270138295
Epoch: 3915  Loss: 79.69635878817081
Epoch: 3916  Loss: 79.73194202909657
Epoch: 3917  Loss: 79.52571150228414
Epoch: 3918  Loss: 79.50429672881477
Epoch: 3919  Loss: 79.40779302309312
Epoc

Epoch: 4183  Loss: 79.85460895810901
Epoch: 4184  Loss: 79.99855628075744
Epoch: 4185  Loss: 79.77801933611332
Epoch: 4186  Loss: 79.6247192106633
Epoch: 4187  Loss: 79.40700064753688
Epoch: 4188  Loss: 79.39797820153308
Epoch: 4189  Loss: 79.35580129253863
Epoch: 4190  Loss: 79.42994771777138
Epoch: 4191  Loss: 79.34269658759226
Epoch: 4192  Loss: 79.39835703062482
Epoch: 4193  Loss: 79.3779108456335
Epoch: 4194  Loss: 79.48458488011501
Epoch: 4195  Loss: 79.63032337856832
Epoch: 4196  Loss: 79.67349736569858
Epoch: 4197  Loss: 79.76321138937817
Epoch: 4198  Loss: 79.80575616320229
Epoch: 4199  Loss: 79.74207441266952
Epoch: 4200  Loss: 79.82804178045754
Epoch: 4201  Loss: 79.64292917693828
Epoch: 4202  Loss: 79.46408160500042
Epoch: 4203  Loss: 79.35006564155584
Epoch: 4204  Loss: 79.35614437370478
Epoch: 4205  Loss: 79.31380128380279
Epoch: 4206  Loss: 79.33975146501321
Epoch: 4207  Loss: 79.27069015795217
Epoch: 4208  Loss: 79.27499887834293
Epoch: 4209  Loss: 79.37082894823942
Epo

Epoch: 4500  Loss: 80.2433561111001
Epoch: 4501  Loss: 80.0137813893391
Epoch: 4502  Loss: 79.80690817081364
Epoch: 4503  Loss: 79.64098874606553
Epoch: 4504  Loss: 79.6400567042773
Epoch: 4505  Loss: 79.47640513463872
Epoch: 4506  Loss: 79.53384733482214
Epoch: 4507  Loss: 79.47579401822016
Epoch: 4508  Loss: 79.55430657663129
Epoch: 4509  Loss: 79.69257530719257
Epoch: 4510  Loss: 79.65889065127097
Epoch: 4511  Loss: 79.6685115329973
Epoch: 4512  Loss: 79.7983850321514
Epoch: 4513  Loss: 79.77168576200047
Epoch: 4514  Loss: 79.92873762394427
Epoch: 4515  Loss: 79.80166973199746
Epoch: 4516  Loss: 79.73344924292735
Epoch: 4517  Loss: 79.61377614045823
Epoch: 4518  Loss: 79.63706708409114
Epoch: 4519  Loss: 79.51471012817878
Epoch: 4520  Loss: 79.56989101638506
Epoch: 4521  Loss: 79.48639720741402
Epoch: 4522  Loss: 79.53592491579175
Epoch: 4523  Loss: 79.50940297777872
Epoch: 4524  Loss: 79.58210739100517
Epoch: 4525  Loss: 79.63844612347967
Epoch: 4526  Loss: 79.77937017148196
Epoch:

Epoch: 4788  Loss: 79.62892387615324
Epoch: 4789  Loss: 79.75864581349794
Epoch: 4790  Loss: 79.85161243536537
Epoch: 4791  Loss: 79.8356457176981
Epoch: 4792  Loss: 80.02419512467422
Epoch: 4793  Loss: 79.9048177048536
Epoch: 4794  Loss: 80.00343668248371
Epoch: 4795  Loss: 79.76749287963716
Epoch: 4796  Loss: 79.73437355996687
Epoch: 4797  Loss: 79.58776855680524
Epoch: 4798  Loss: 79.5711766856312
Epoch: 4799  Loss: 79.42845971461483
Epoch: 4800  Loss: 79.44604907817467
Epoch: 4801  Loss: 79.43840436398519
Epoch: 4802  Loss: 79.57956051602615
Epoch: 4803  Loss: 79.72028341405142
Epoch: 4804  Loss: 79.86071248718659
Epoch: 4805  Loss: 79.90962896878216
Epoch: 4806  Loss: 79.97211755216244
Epoch: 4807  Loss: 79.962118504759
Epoch: 4808  Loss: 80.11045194769393
Epoch: 4809  Loss: 79.8869768749142
Epoch: 4810  Loss: 79.78246833066865
Epoch: 4811  Loss: 79.65042140614091
Epoch: 4812  Loss: 79.58965828242754
Epoch: 4813  Loss: 79.4186245104613
Epoch: 4814  Loss: 79.43943847169858
Epoch: 4

Epoch: 5097  Loss: 79.39285887284873
Epoch: 5098  Loss: 79.44244082775535
Epoch: 5099  Loss: 79.42645732331265
Epoch: 5100  Loss: 79.52711149788676
Epoch: 5101  Loss: 79.66551575814283
Epoch: 5102  Loss: 79.84884264052405
Epoch: 5103  Loss: 79.90488831377192
Epoch: 5104  Loss: 79.85725254293223
Epoch: 5105  Loss: 79.91712114810234
Epoch: 5106  Loss: 80.13995573273688
Epoch: 5107  Loss: 79.87918183204313
Epoch: 5108  Loss: 79.77830636600044
Epoch: 5109  Loss: 79.68479368810596
Epoch: 5110  Loss: 79.56450897730514
Epoch: 5111  Loss: 79.36550239105212
Epoch: 5112  Loss: 79.43019234842086
Epoch: 5113  Loss: 79.39968530389014
Epoch: 5114  Loss: 79.47742180598595
Epoch: 5115  Loss: 79.6626925693483
Epoch: 5116  Loss: 79.87357787835569
Epoch: 5117  Loss: 79.965264003012
Epoch: 5118  Loss: 79.82655084194488
Epoch: 5119  Loss: 79.93907742804517
Epoch: 5120  Loss: 80.19303074563781
Epoch: 5121  Loss: 79.89600957769906
Epoch: 5122  Loss: 79.7733602373934
Epoch: 5123  Loss: 79.67449902879731
Epoch

Epoch: 5387  Loss: 79.85389533861064
Epoch: 5388  Loss: 79.93219296418387
Epoch: 5389  Loss: 79.89607797127903
Epoch: 5390  Loss: 80.0658528740168
Epoch: 5391  Loss: 79.8429686165413
Epoch: 5392  Loss: 79.77571627889836
Epoch: 5393  Loss: 79.66103669164201
Epoch: 5394  Loss: 79.59710088083347
Epoch: 5395  Loss: 79.42759600257284
Epoch: 5396  Loss: 79.44408092925633
Epoch: 5397  Loss: 79.4261262159549
Epoch: 5398  Loss: 79.534035971312
Epoch: 5399  Loss: 79.67117316825397
Epoch: 5400  Loss: 79.8525832536987
Epoch: 5401  Loss: 79.91231604164923
Epoch: 5402  Loss: 79.84214600182855
Epoch: 5403  Loss: 79.90977436240584
Epoch: 5404  Loss: 80.1252504112953
Epoch: 5405  Loss: 79.88393154158835
Epoch: 5406  Loss: 79.7989447190483
Epoch: 5407  Loss: 79.71485169560407
Epoch: 5408  Loss: 79.57318992122049
Epoch: 5409  Loss: 79.37656641004612
Epoch: 5410  Loss: 79.41980416691429
Epoch: 5411  Loss: 79.41189376269627
Epoch: 5412  Loss: 79.47706489125045
Epoch: 5413  Loss: 79.66408077001114
Epoch: 54

Epoch: 5688  Loss: 80.04300056195271
Epoch: 5689  Loss: 79.8284287917685
Epoch: 5690  Loss: 79.77697980251507
Epoch: 5691  Loss: 79.66255441871832
Epoch: 5692  Loss: 79.58258060243459
Epoch: 5693  Loss: 79.41529482493483
Epoch: 5694  Loss: 79.42252236901138
Epoch: 5695  Loss: 79.41614384177498
Epoch: 5696  Loss: 79.5316512274351
Epoch: 5697  Loss: 79.66184017982475
Epoch: 5698  Loss: 79.85440941359614
Epoch: 5699  Loss: 79.90663526517027
Epoch: 5700  Loss: 79.87775551205256
Epoch: 5701  Loss: 79.95943578917644
Epoch: 5702  Loss: 80.17746650043925
Epoch: 5703  Loss: 79.91717911530836
Epoch: 5704  Loss: 79.83882434339183
Epoch: 5705  Loss: 79.7447908115426
Epoch: 5706  Loss: 79.5689770830594
Epoch: 5707  Loss: 79.3695562194645
Epoch: 5708  Loss: 79.42928543706327
Epoch: 5709  Loss: 79.43572602971717
Epoch: 5710  Loss: 79.49522266404759
Epoch: 5711  Loss: 79.65759113619738
Epoch: 5712  Loss: 79.90040247224944
Epoch: 5713  Loss: 79.97842295012885
Epoch: 5714  Loss: 79.86395733824062
Epoch:

Epoch: 5974  Loss: 79.77744235770109
Epoch: 5975  Loss: 79.66797222018903
Epoch: 5976  Loss: 79.60889668666289
Epoch: 5977  Loss: 79.43626501743404
Epoch: 5978  Loss: 79.41776213695775
Epoch: 5979  Loss: 79.39759145690495
Epoch: 5980  Loss: 79.50242934394201
Epoch: 5981  Loss: 79.6377490937283
Epoch: 5982  Loss: 79.8726028174626
Epoch: 5983  Loss: 79.94920956490023
Epoch: 5984  Loss: 79.84266246825757
Epoch: 5985  Loss: 79.94999858837448
Epoch: 5986  Loss: 80.2074065124151
Epoch: 5987  Loss: 79.93500558832915
Epoch: 5988  Loss: 79.80050413819596
Epoch: 5989  Loss: 79.69286193931552
Epoch: 5990  Loss: 79.60286543407405
Epoch: 5991  Loss: 79.41168020582107
Epoch: 5992  Loss: 79.43453374507727
Epoch: 5993  Loss: 79.41344460935055
Epoch: 5994  Loss: 79.47524127920173
Epoch: 5995  Loss: 79.64697710031221
Epoch: 5996  Loss: 79.92714990863401
Epoch: 5997  Loss: 80.03170867282144
Epoch: 5998  Loss: 79.82561017233982
Epoch: 5999  Loss: 79.95322992208624
Epoch: 6000  Loss: 80.22727069152235
Epoc

Epoch: 6283  Loss: 79.8637212899615
Epoch: 6284  Loss: 80.12708331010832
Epoch: 6285  Loss: 79.86565872018124
Epoch: 6286  Loss: 79.75928613091075
Epoch: 6287  Loss: 79.68946356137302
Epoch: 6288  Loss: 79.6486892222014
Epoch: 6289  Loss: 79.46371152193049
Epoch: 6290  Loss: 79.46592756230669
Epoch: 6291  Loss: 79.42005579138916
Epoch: 6292  Loss: 79.55078510987637
Epoch: 6293  Loss: 79.6025737389827
Epoch: 6294  Loss: 79.7348920677939
Epoch: 6295  Loss: 79.71813947626596
Epoch: 6296  Loss: 79.67100584614606
Epoch: 6297  Loss: 79.6935078746711
Epoch: 6298  Loss: 79.97984555771247
Epoch: 6299  Loss: 79.75819681196398
Epoch: 6300  Loss: 79.69126486793921
Epoch: 6301  Loss: 79.60159634952822
Epoch: 6302  Loss: 79.60687224740327
Epoch: 6303  Loss: 79.42114740253703
Epoch: 6304  Loss: 79.39853098703345
Epoch: 6305  Loss: 79.32194158643823
Epoch: 6306  Loss: 79.50288713648663
Epoch: 6307  Loss: 79.59096038446371
Epoch: 6308  Loss: 79.83401103435114
Epoch: 6309  Loss: 79.87004447413979
Epoch:

Epoch: 6593  Loss: 79.58861448235436
Epoch: 6594  Loss: 79.72610294258718
Epoch: 6595  Loss: 79.58344089737075
Epoch: 6596  Loss: 79.61786999045216
Epoch: 6597  Loss: 79.72686248399418
Epoch: 6598  Loss: 79.65368140839978
Epoch: 6599  Loss: 79.60613560682522
Epoch: 6600  Loss: 79.61921905781482
Epoch: 6601  Loss: 79.68677692739598
Epoch: 6602  Loss: 79.94853135140058
Epoch: 6603  Loss: 79.77697633534913
Epoch: 6604  Loss: 79.74161846812625
Epoch: 6605  Loss: 79.59465098012603
Epoch: 6606  Loss: 79.6043084472854
Epoch: 6607  Loss: 79.48327862070377
Epoch: 6608  Loss: 79.56427349640569
Epoch: 6609  Loss: 79.49885587884812
Epoch: 6610  Loss: 79.62675662440161
Epoch: 6611  Loss: 79.67206011449468
Epoch: 6612  Loss: 79.6293913515573
Epoch: 6613  Loss: 79.70558297406455
Epoch: 6614  Loss: 79.83437359880777
Epoch: 6615  Loss: 79.84362242939808
Epoch: 6616  Loss: 79.98882784130201
Epoch: 6617  Loss: 79.90431208986777
Epoch: 6618  Loss: 79.93710632197852
Epoch: 6619  Loss: 79.80251482981427
Epo

Epoch: 6865  Loss: 79.47807990737495
Epoch: 6866  Loss: 79.49776409212475
Epoch: 6867  Loss: 79.36970488819111
Epoch: 6868  Loss: 79.40784990538548
Epoch: 6869  Loss: 79.34251471224292
Epoch: 6870  Loss: 79.47348432807523
Epoch: 6871  Loss: 79.67172135377808
Epoch: 6872  Loss: 79.87219780827543
Epoch: 6873  Loss: 80.04433532093263
Epoch: 6874  Loss: 79.92105903482094
Epoch: 6875  Loss: 79.96051320387733
Epoch: 6876  Loss: 80.20052226268967
Epoch: 6877  Loss: 80.10516766118884
Epoch: 6878  Loss: 80.0100940190976
Epoch: 6879  Loss: 79.78293029168267
Epoch: 6880  Loss: 79.84313606194537
Epoch: 6881  Loss: 79.6592293084941
Epoch: 6882  Loss: 79.57768636528778
Epoch: 6883  Loss: 79.39005149191698
Epoch: 6884  Loss: 79.4674021196413
Epoch: 6885  Loss: 79.50792972564633
Epoch: 6886  Loss: 79.7371741181156
Epoch: 6887  Loss: 79.86450365966651
Epoch: 6888  Loss: 79.95433705615139
Epoch: 6889  Loss: 79.90240773612346
Epoch: 6890  Loss: 80.15456127439583
Epoch: 6891  Loss: 80.02023065441252
Epoch

Epoch: 7213  Loss: 79.4012798450207
Epoch: 7214  Loss: 79.46976969761158
Epoch: 7215  Loss: 79.59985963575946
Epoch: 7216  Loss: 79.89413154955014
Epoch: 7217  Loss: 80.01772671579343
Epoch: 7218  Loss: 79.73591293032396
Epoch: 7219  Loss: 79.77194654669101
Epoch: 7220  Loss: 80.07089347779868
Epoch: 7221  Loss: 79.86309233914609
Epoch: 7222  Loss: 79.72265684100277
Epoch: 7223  Loss: 79.56527543533402
Epoch: 7224  Loss: 79.6303347148239
Epoch: 7225  Loss: 79.47991270289307
Epoch: 7226  Loss: 79.46582805757023
Epoch: 7227  Loss: 79.30310076370958
Epoch: 7228  Loss: 79.39282856606599
Epoch: 7229  Loss: 79.49469299557772
Epoch: 7230  Loss: 79.74220897737986
Epoch: 7231  Loss: 79.89106928515051
Epoch: 7232  Loss: 79.7176120272552
Epoch: 7233  Loss: 79.71473513876697
Epoch: 7234  Loss: 80.01562835624746
Epoch: 7235  Loss: 79.87993592357749
Epoch: 7236  Loss: 79.82314505651172
Epoch: 7237  Loss: 79.60343110483565
Epoch: 7238  Loss: 79.63575105813757
Epoch: 7239  Loss: 79.49603069693714
Epoc

Epoch: 7489  Loss: 79.9027314142919
Epoch: 7490  Loss: 79.77114496252388
Epoch: 7491  Loss: 79.82494404328932
Epoch: 7492  Loss: 80.13770772409651
Epoch: 7493  Loss: 79.87667307505929
Epoch: 7494  Loss: 79.76770051184674
Epoch: 7495  Loss: 79.65195692169166
Epoch: 7496  Loss: 79.65969267931906
Epoch: 7497  Loss: 79.47674638983845
Epoch: 7498  Loss: 79.46082132962908
Epoch: 7499  Loss: 79.3953477577788
Epoch: 7500  Loss: 79.4871941971911
Epoch: 7501  Loss: 79.60319653943775
Epoch: 7502  Loss: 79.96504052840481
Epoch: 7503  Loss: 80.09402115133324
Epoch: 7504  Loss: 79.83173807684176
Epoch: 7505  Loss: 79.9152709971643
Epoch: 7506  Loss: 80.21709141229556
Epoch: 7507  Loss: 79.91834896981788
Epoch: 7508  Loss: 79.74674360011156
Epoch: 7509  Loss: 79.5913487197519
Epoch: 7510  Loss: 79.61733628945314
Epoch: 7511  Loss: 79.44104060514992
Epoch: 7512  Loss: 79.4879447848115
Epoch: 7513  Loss: 79.37226945625885
Epoch: 7514  Loss: 79.43693063405715
Epoch: 7515  Loss: 79.5808328471436
Epoch: 7

Epoch: 7837  Loss: 79.78140568421071
Epoch: 7838  Loss: 79.76092041632215
Epoch: 7839  Loss: 79.63691461592543
Epoch: 7840  Loss: 79.61529174167605
Epoch: 7841  Loss: 79.46823085095099
Epoch: 7842  Loss: 79.42925146494456
Epoch: 7843  Loss: 79.40988554592128
Epoch: 7844  Loss: 79.56384257109286
Epoch: 7845  Loss: 79.66671407168849
Epoch: 7846  Loss: 79.897903259209
Epoch: 7847  Loss: 79.92815071505939
Epoch: 7848  Loss: 79.96386858195443
Epoch: 7849  Loss: 80.01297543588814
Epoch: 7850  Loss: 80.23370936198621
Epoch: 7851  Loss: 79.95950519033111
Epoch: 7852  Loss: 79.8573108266433
Epoch: 7853  Loss: 79.7491787308341
Epoch: 7854  Loss: 79.64343776420225
Epoch: 7855  Loss: 79.46009816595141
Epoch: 7856  Loss: 79.46193376292109
Epoch: 7857  Loss: 79.4698963408303
Epoch: 7858  Loss: 79.56475995645874
Epoch: 7859  Loss: 79.64650242866756
Epoch: 7860  Loss: 79.87923867736724
Epoch: 7861  Loss: 79.90382231195053
Epoch: 7862  Loss: 79.80505228984686
Epoch: 7863  Loss: 79.87558691775381
Epoch:

Epoch: 8127  Loss: 79.2994469972451
Epoch: 8128  Loss: 79.43665614363955
Epoch: 8129  Loss: 79.52017477251071
Epoch: 8130  Loss: 79.8332417171275
Epoch: 8131  Loss: 79.93065363762925
Epoch: 8132  Loss: 79.86914132078151
Epoch: 8133  Loss: 79.8672241148532
Epoch: 8134  Loss: 80.19988253476679
Epoch: 8135  Loss: 79.9856931088953
Epoch: 8136  Loss: 79.88760905914283
Epoch: 8137  Loss: 79.69029370385671
Epoch: 8138  Loss: 79.93588256623605
Epoch: 8139  Loss: 79.86046759403855
Epoch: 8140  Loss: 79.5869669332291
Epoch: 8141  Loss: 79.41390476585192
Epoch: 8142  Loss: 79.54538408897076
Epoch: 8143  Loss: 79.58436614791823
Epoch: 8144  Loss: 79.73797854652126
Epoch: 8145  Loss: 79.74298029288556
Epoch: 8146  Loss: 79.68110740802653
Epoch: 8147  Loss: 79.65166326216324
Epoch: 8148  Loss: 79.95692192590218
Epoch: 8149  Loss: 79.78961591350352
Epoch: 8150  Loss: 79.73379578222082
Epoch: 8151  Loss: 79.6448895941114
Epoch: 8152  Loss: 79.79124707576659
Epoch: 8153  Loss: 79.64314270192887
Epoch: 

Epoch: 8441  Loss: 79.79614782735433
Epoch: 8442  Loss: 80.04376410908372
Epoch: 8443  Loss: 79.843288099602
Epoch: 8444  Loss: 79.76012622796463
Epoch: 8445  Loss: 79.56762209306426
Epoch: 8446  Loss: 79.58244872874421
Epoch: 8447  Loss: 79.44754818120084
Epoch: 8448  Loss: 79.50377968705774
Epoch: 8449  Loss: 79.39400932595402
Epoch: 8450  Loss: 79.4935952926999
Epoch: 8451  Loss: 79.56738085304441
Epoch: 8452  Loss: 79.6580257360814
Epoch: 8453  Loss: 79.80385245904378
Epoch: 8454  Loss: 79.8910040132549
Epoch: 8455  Loss: 79.93898857131502
Epoch: 8456  Loss: 80.12474192597767
Epoch: 8457  Loss: 80.05470751224755
Epoch: 8458  Loss: 80.1351729729756
Epoch: 8459  Loss: 79.97769666369196
Epoch: 8460  Loss: 79.90781321814814
Epoch: 8461  Loss: 79.72561061283241
Epoch: 8462  Loss: 79.73916062579069
Epoch: 8463  Loss: 79.6150992092215
Epoch: 8464  Loss: 79.59632787363216
Epoch: 8465  Loss: 79.54713228025032
Epoch: 8466  Loss: 79.63947036780549
Epoch: 8467  Loss: 79.67778412766927
Epoch: 8

Epoch: 8739  Loss: 79.93869563996887
Epoch: 8740  Loss: 79.90332885355612
Epoch: 8741  Loss: 79.7024741259032
Epoch: 8742  Loss: 79.72359772685559
Epoch: 8743  Loss: 79.5613073133486
Epoch: 8744  Loss: 79.48557726144546
Epoch: 8745  Loss: 79.32009783217212
Epoch: 8746  Loss: 79.40130746994018
Epoch: 8747  Loss: 79.4551076377455
Epoch: 8748  Loss: 79.7050326777355
Epoch: 8749  Loss: 79.83641036823843
Epoch: 8750  Loss: 79.8036758317203
Epoch: 8751  Loss: 79.7715788662097
Epoch: 8752  Loss: 80.03421093889635
Epoch: 8753  Loss: 79.91240560823476
Epoch: 8754  Loss: 79.93607938076252
Epoch: 8755  Loss: 79.68477692351861
Epoch: 8756  Loss: 79.77934426816692
Epoch: 8757  Loss: 79.6636896109989
Epoch: 8758  Loss: 79.50518511330125
Epoch: 8759  Loss: 79.34325677955803
Epoch: 8760  Loss: 79.4441904703135
Epoch: 8761  Loss: 79.47473394669126
Epoch: 8762  Loss: 79.71839833051271
Epoch: 8763  Loss: 79.87770543086447
Epoch: 8764  Loss: 79.80731882816693
Epoch: 8765  Loss: 79.79072638158374
Epoch: 87

Epoch: 9069  Loss: 79.71720151182832
Epoch: 9070  Loss: 79.70670807012517
Epoch: 9071  Loss: 79.58584113744274
Epoch: 9072  Loss: 79.4823216732155
Epoch: 9073  Loss: 79.29485421454297
Epoch: 9074  Loss: 79.40807720697279
Epoch: 9075  Loss: 79.4226531112786
Epoch: 9076  Loss: 79.53667683649793
Epoch: 9077  Loss: 79.64969596573425
Epoch: 9078  Loss: 79.73692412473446
Epoch: 9079  Loss: 79.72803869867565
Epoch: 9080  Loss: 79.89586106061026
Epoch: 9081  Loss: 79.843579010549
Epoch: 9082  Loss: 80.0341352691588
Epoch: 9083  Loss: 79.80621022853796
Epoch: 9084  Loss: 79.7145016669123
Epoch: 9085  Loss: 79.59418036330504
Epoch: 9086  Loss: 79.57374111824456
Epoch: 9087  Loss: 79.42924655735945
Epoch: 9088  Loss: 79.46124131119339
Epoch: 9089  Loss: 79.44826162353854
Epoch: 9090  Loss: 79.64829659167664
Epoch: 9091  Loss: 79.77656297139107
Epoch: 9092  Loss: 79.89059764175826
Epoch: 9093  Loss: 79.90845603325118
Epoch: 9094  Loss: 79.9828160094516
Epoch: 9095  Loss: 79.92914251242497
Epoch: 9

Epoch: 9352  Loss: 80.08748803582668
Epoch: 9353  Loss: 79.9050357841513
Epoch: 9354  Loss: 79.87353595202343
Epoch: 9355  Loss: 79.60852846737099
Epoch: 9356  Loss: 79.6575425863916
Epoch: 9357  Loss: 79.52166182910653
Epoch: 9358  Loss: 79.47089596506838
Epoch: 9359  Loss: 79.30656714953577
Epoch: 9360  Loss: 79.38805040510374
Epoch: 9361  Loss: 79.43026175076426
Epoch: 9362  Loss: 79.658293371953
Epoch: 9363  Loss: 79.81776716780556
Epoch: 9364  Loss: 79.84610180923542
Epoch: 9365  Loss: 79.83672874147143
Epoch: 9366  Loss: 80.1213338923749
Epoch: 9367  Loss: 80.00699420094739
Epoch: 9368  Loss: 80.08110043084628
Epoch: 9369  Loss: 79.7940339494446
Epoch: 9370  Loss: 79.75203498481571
Epoch: 9371  Loss: 79.63425834243803
Epoch: 9372  Loss: 79.5648013366861
Epoch: 9373  Loss: 79.41471286294693
Epoch: 9374  Loss: 79.49048837573145
Epoch: 9375  Loss: 79.50731272649719
Epoch: 9376  Loss: 79.61816913437245
Epoch: 9377  Loss: 79.73755455534007
Epoch: 9378  Loss: 79.84632363573174
Epoch: 9

Epoch: 9686  Loss: 79.60454003379971
Epoch: 9687  Loss: 79.41570951340003
Epoch: 9688  Loss: 79.41264184187663
Epoch: 9689  Loss: 79.34739650847823
Epoch: 9690  Loss: 79.52200236354417
Epoch: 9691  Loss: 79.70471266705154
Epoch: 9692  Loss: 79.96232483549532
Epoch: 9693  Loss: 80.00771596631019
Epoch: 9694  Loss: 79.98117293451088
Epoch: 9695  Loss: 80.0534176983233
Epoch: 9696  Loss: 80.34125950450652
Epoch: 9697  Loss: 79.97920443312341
Epoch: 9698  Loss: 79.91567643041176
Epoch: 9699  Loss: 79.81629961120952
Epoch: 9700  Loss: 79.65466208519221
Epoch: 9701  Loss: 79.39609133452166
Epoch: 9702  Loss: 79.47478597480789
Epoch: 9703  Loss: 79.42720377326529
Epoch: 9704  Loss: 79.46518702539133
Epoch: 9705  Loss: 79.61194857692752
Epoch: 9706  Loss: 80.0019261885566
Epoch: 9707  Loss: 80.14861552173565
Epoch: 9708  Loss: 80.02310102673923
Epoch: 9709  Loss: 80.1092835584145
Epoch: 9710  Loss: 80.32009327145454
Epoch: 9711  Loss: 79.99089957176255
Epoch: 9712  Loss: 79.82038021979497
Epoc

Epoch: 9971  Loss: 79.95691803503972
Epoch: 9972  Loss: 80.13088276377476
Epoch: 9973  Loss: 79.94781474294322
Epoch: 9974  Loss: 79.96642520568555
Epoch: 9975  Loss: 79.71182121281818
Epoch: 9976  Loss: 79.78780252061304
Epoch: 9977  Loss: 79.70436326518887
Epoch: 9978  Loss: 79.6809378957204
Epoch: 9979  Loss: 79.46194767517063
Epoch: 9980  Loss: 79.48472483025971
Epoch: 9981  Loss: 79.47617950619005
Epoch: 9982  Loss: 79.645987373569
Epoch: 9983  Loss: 79.63298518760266
Epoch: 9984  Loss: 79.90270537554497
Epoch: 9985  Loss: 79.87254994698361
Epoch: 9986  Loss: 80.03009983891792
Epoch: 9987  Loss: 79.96334654328699
Epoch: 9988  Loss: 80.16322814624857
Epoch: 9989  Loss: 79.88480116251682
Epoch: 9990  Loss: 79.90905654150225
Epoch: 9991  Loss: 79.7987826220509
Epoch: 9992  Loss: 79.59334372571956
Epoch: 9993  Loss: 79.37707556256838
Epoch: 9994  Loss: 79.56808028279485
Epoch: 9995  Loss: 79.53333123385025
Epoch: 9996  Loss: 79.66195458549576
Epoch: 9997  Loss: 79.61249071635427
Epoch

In [18]:
emb = params['Wh']
emb[0]
print(emb.shape)

(9, 10)
